### ISSUE TITLE
TransmitterPdu missing initial padding field

### ISSUE THREAD

**Issue by arrowsmith** [open-dis/opendis7-java#10]
Hi again Don @brutzman ,

According to [this breakdown](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/dc.htm), the `TransmitterPdu` needs to have a 16-bit padding field for marshalling / unmarshalling after the `InputSource` field, but the implementation misses it. There's only the later 24-bit padding field handled as a byte and a short.

**Comment by arrowsmith** [comment]
Can I tag anyone else on this? @leif81 @blueoak @terry-norbraten ? How are issues best raised and handled?

**Comment by leif81** [comment]
Thanks for report @arrowsmith . This is the right place to log issues. For this repository @brutzman is the maintainer. When he has a moment to review I'm sure he'll let you know here. Cheers.

**Comment by brutzman** [comment]
Yes thanks for the report Arrowsmith.  The report you link is pretty dated, we're using more recent references.

Most of the open-dis7-java PDUs are correct but you may be quite right that some PDU marshalling/unmarshalling is incorrect.

I now see you have had a lot of posts Austin.  Looking forward to getting going again, will be happy to improve our information sharing and implementation.  Please see my next post for further information.

**Comment by terry-norbraten** [comment]
@arrowsmith Hello Austin, the protocols for all PDUs in this project are IAW IEEE Std 1278.1-2012. The link you provided above is likely from older versions of both IEEE Std 1278.1-1995 and the material included in the
IEEE Std 1278.1a-1998 amendment, which have been superseded. Older implementation of OpenDIS at https://github.com/open-dis/open-dis-java and even https://sourceforge.net/projects/open-dis, might have the TransmitterPDU in the format you were looking for.

**Comment by brutzman** [comment]
p.s. looks like unit tests are working, but we have more integration and documentation to achieve.  We are further exploring additional variations of DIS XML and Data Format Definition Language (DFDL) etc.  One of our current goals is to make all of this more accessible for contributions in the coming year.
