### ISSUE TITLE
Wrong case in file names

### ISSUE THREAD

**Issue by federkamm** [open-dis/opendis7-java#16]
I can't compile the project with lots of errors like

    C:\path\to\opendis7-java\src-generated\edu\nps\moves\dis7\entities\chn\platform\land\CSSC6HY3Sawhorselauncher.java:31:
    error: class CSSC6HY3SawhorseLauncher is public, should be declared in a file named CSSC6HY3SawhorseLauncher.java
    public final class CSSC6HY3SawhorseLauncher extends EntityType

The problem is the wrong case in the file name `CSSC6HY3Sawhorselauncher.java` instead of `CSSC6HY3SawhorseLauncher.java` (with capital `L` in `Launcher`).

I can fix this locally on my machine but I think the repo should be updated as well.  It's difficult however to generate a pull-request, since I'm on Windows and Git on Windows doesn't understand the file name has changed if it's only different by case.  Maybe someone on Linux has to do it.

**Comment by federkamm** [comment]
I figured out how to make a pull request for this issue: #17

Since the changes are in src-generated, probably opendis7-source-generator has to be fixed in order to make the change permanent.  However, this PR shows what should be changed.

**Comment by brutzman** [comment]
repo was fixed, thanks.  closing stale branch.
