### ISSUE TITLE
HQ16TrackingandGuidanceRADARVehicle case-insensitive filesystem collision

### ISSUE THREAD

**Issue by ricklentz** [open-dis/opendis7-java#18]
There seems to be two similar versions of the following class:  HQ16TrackingandGuidanceRADARVehicle

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src-generated/edu/nps/moves/dis7/entities/chn/platform/land/HQ16TrackingandGuidanceRADARVehicle.java'
  'src-generated/edu/nps/moves/dis7/entities/chn/platform/land/HQ16TrackingandGuidanceRadarVehicle.java'

Should we remove one of them?

**Comment by terry-norbraten** [comment]
Confirmed that only a single class, the later, is generated from [opendis7-source-generator](https://github.com/open-dis/opendis7-source-generator).
