### ISSUE TITLE
No call of registered typed listeners without at least registering one untyped 

### ISSUE THREAD

**Issue by cruncher64** [open-dis/opendis7-java#22]
In the toListeners method of DisThreadedNetworkInterface the first code block requires, that one has to register at least one untyped listener (i.e. listener without reference to DisPduType) to get the typed listeners to be informed. This is an unexpected behaviour and should be changed.

**Comment by terry-norbraten** [comment]
Agreed, that was a poorly written method, fixed in (9c23b2abc1e614cf584c8c153f2e5b4871a7e6bf).
