### ISSUE TITLE
Thread safety for PDU classes

### ISSUE THREAD

**Issue by brutzman** [open-dis/opendis7-java#24]
Found an interesting problem in [DisThreadedNetworkInterface](https://github.com/open-dis/opendis7-java/blob/master/src/edu/nps/moves/dis7/utilities/DisThreadedNetworkInterface.java).selfTest() method where ESPDU changes to marking values were getting clobbered during fast sends/updates.  This was shown by print statements showing the same marking value in rapid progression (rather than marking 1, marking 2, etc.).

Avoided this problem (for now) by creating a new PDU each time.  I think this anomaly indicates that the library isn't fully thread safe, e.g. an ESPDU instance might get modified while still being sent (or reported upon).  Some more thought will be needed for making all PDU methods thread safe.

Log of test results found in [DisThreadedNetworkInterfaceSelfTestLog.txt](https://github.com/open-dis/opendis7-java/blob/master/src/edu/nps/moves/dis7/utilities/DisThreadedNetworkInterfaceSelfTestLog.txt)

**Comment by brutzman** [comment]
Problem definition:

- User invokes sending a PDU, which is then temporarily blocked while synchronized send buffers are processed
- User modifies that object before the send occurs
- PDU actually being sent does not match the PDU originally sent

Any performance reduction from synchronization is miniscule in comparison to possible loss of object integrity.  Indeed synchronization blocking only occurs if it is needed.

Next steps:

- add keyword _synchronized_ to all "set" accessor methods

**Comment by terry-norbraten** [comment]
FixedAndVariableDatumRoundTripTest is now fixed (Issue #26)

**Comment by brutzman** [comment]
@terry-norbraten has also fixed some unnecessary duplicate creation of DISThreadedNetworkInterface instance in PduRecorder, further helping with threading.
