### ISSUE TITLE
upgrade tests to JUnit5

### ISSUE THREAD

**Issue by brutzman** [open-dis/opendis7-java#3]
Individual test programs all compile and run individually, but not as part of the project.

Likely needs adjustment or upgrade of old test code to match JUnit5.

Typical output:

> Testsuite: edu.nps.moves.dis7.CreateAllObjectTypesTest
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.428 sec
> 
> Testcase: initializationError(edu.nps.moves.dis7.CreateAllObjectTypesTest):	Caused an ERROR
> No runnable methods
> java.lang.Exception: No runnable methods
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)

**Comment by terry-norbraten** [comment]
All unit tests pass with JUnit5 + JUnit Jupiter test libs.
