### ISSUE TITLE
RadioType class is broken

### ISSUE THREAD

**Issue by arrowsmith** [open-dis/opendis7-java#8]
Hi @brutzman,

According to [this page](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/de.htm), the RadioType should contain only 6 fields, but the resulting implementation contains 7. It starts off with field names that match - EntityKind, Domain, Country, and then Category, but after that the implementation has Subcategory, Specific, and Extra, which are not in the standard. There's no mention of the [Nomenclature](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/e3.htm), or [Nomenclature version](http://faculty.nps.edu/brutzman/vrtp/mil/navy/nps/disEnumerations/JdbeHtmlFiles/pdu/e2.htm) fields. Essentially, the unmarshalling pulls out 9 bytes from the PDU instead of the 8 bytes that it should for this field.

I noticed activity has picked up on the repo recently. Any chance of this one being fixed soon?

**Comment by terry-norbraten** [comment]
@arrowsmith The record components, the link above is out of date (we should either update, or take that site down as it's stale). The RadioType is implemented in accordance with the current standard.
<img width="766" alt="Screen Shot 2023-11-12 at 09 45 45" src="https://github.com/open-dis/opendis7-java/assets/6370489/15aac14d-3896-4e72-bb8a-5b074510e743">
